### ISSUE TITLE
NameError: undefined method `append_info_to_payload' for class `ActionCable::Channel::Base'

### ISSUE THREAD

**Issue by kntmrkm** [roidrage/lograge#285]
After upgraded `0.11.0`.

Got a below error.

```
NameError: undefined method `append_info_to_payload' for class `ActionCable::Channel::Base'
```

with this setting 

```
config.lograge.custom_payload do |controller|
        {
          user_agent: controller.request.user_agent,
        }
      end    
```

**Comment by decoch** [comment]
+1

**Comment by decoch** [comment]
I am also facing the same issue.
Could I prevent this but there is no problem?

```ruby
# config/initializers/lograge.rb
config.lograge.base_controller_class = 'ActionController::Base'
```

**Comment by barrettclark** [comment]
I'm getting this error as well, but only when I run the asset precompile rake task in a Docker container. The application and rake tasks work fine locally. Weird.

Adding the initializer allows me to precompile assets in the container, but I had to tweak it a little to define the config:

```ruby
# frozen_string_literal: true
Rails.application.config.lograge.base_controller_class = "ActionController::Base"
```

It seems to work fine. I am not using ActionCable in this app.

Thanks for the tip @decoch

**Comment by benlovell** [comment]
Sorry about this folks. I’m working on a fix.

**Comment by collimarco** [comment]
I have the same issue. Everything works fine on `v0.10.0`, while I get the error on `v0.11.0`. I am using the latest version of Rails (`v5.2.3`).

**Comment by xlts** [comment]
Sorry guys, that's my fault, I did overlook the `custom_payload` option when implementing Action Cable log formatting. Here's the PR with the fix: https://github.com/roidrage/lograge/pull/286 (cc @benlovell)

As for the option itself, we should figure out the way `custom_payload` would work in Action Cable classes. Maybe it'd be good to support formatters for each event (`perform_action`, `subscribe`, `unsubscribe` ...) or for each class, as `ActionCable::Connection::Base` and `ActionCable::Channel::Base` don't share a common context.

**Comment by billdueber** [comment]
I still see this under 0.11.0 -- a quick look shows the code in the 0.11.0 tag doesn't have the fix from #286 in it (see https://github.com/roidrage/lograge/blob/244ce405f674f0c66d043c32f2d98edd118c4f36/lib/lograge.rb#L169-L172). Are you planning a release that includes it?

**Comment by benlovell** [comment]
I've just released 0.11.1 including this fix.

**Comment by billdueber** [comment]
If what I referenced above is the problematic code, it's unchanged in 0.11.1

**Comment by CHTJonas** [comment]
Likewise error is still occurring here 😢 This needs to be reopened @benlovell.

**Comment by benlovell** [comment]
Ugh. I’ll get this resolved properly tomorrow. Apologies folks.

**Comment by billdueber** [comment]
Hey, it's open source on a Friday afternoon. Don't apologize too hard 😄

**Comment by benbartling** [comment]
Just want to bring this one back up. Can we get #286 merged?

**Comment by xlts** [comment]
@benlovell please let us know if there's anything preventing https://github.com/roidrage/lograge/pull/286 from being merged 🙂

**Comment by benlovell** [comment]
I'm not 100% convinced this resolves the issue. It has no test that verifies the behaviour so I have to set up a project myself to verify it manually and I'm reluctant to do this as something previously touted as a fix was not. If someone adds a spec for it I'll merge it right away. I've just not had the bandwidth to take care of it myself :(

**Comment by benlovell** [comment]
@xlts It works locally, if you could add a spec when you get a moment that would help. I'll cut a release with the fix now.
