### ISSUE TITLE
Errors in Action Cable log after update to 0.11.0

### ISSUE THREAD

**Issue by alabamaair** [roidrage/lograge#287]
Rails 5.0.2, development mode. After update lograge to 0.11.0 I got errors in log:
```[ActionCable] [Admin] [lvh.me] There was an exception - NoMethodError(undefined method `config' for nil:NilClass)
[ActionCable] [Admin] [lvh.me] /Users/alabama/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/lograge-0.11.0/lib/lograge.rb:228:in `lograge_config'
/Users/alabama/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/lograge-0.11.0/lib/lograge/rails_ext/action_cable/connection/base.rb:24:in `block in handle_close'
/Users/alabama/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:166:in `instrument' ...``` 
...

If add to development.rb `config.lograge.enabled = true` - errors disappear, but if no need "lograge" in development mode and add `config.lograge.enabled = false` - errors still going on.

Sorry for my english.

**Comment by xlts** [comment]
@alabamaair, thanks for reporting this. Will post a PR with a fix today
